@baseUrl = http://localhost:3333
// @authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "passwordTest123"
}
